language: node_js
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- bower install --silent"
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "multipart-payload-editor:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: FTFC/mMQx6kJDiF9hqWVhkXV5aMhBI7+Z0WDk7vB+6FbdqX2wmZZ3XA19h389t181Kob/1V+IcX1CDwJDnijCa9NJ7FmYkqnExl3KyM240GzFhVha1iY9Ax2O5D0ziDrGm6dHpaVqesQLNcRq1ksbQeR3ixCHVDzGiM74LzTdBc9za95gZ9MiBFmxmjj1IYhATC5Ll9R9aW7bjbYkZHD6BjAI8O7ISIswsB+zi97fJ/tRQ9kVhEu4ooYCL3eFWhMBJjfk6xYzdnHChYDl2GZEHB/UcPaXAQlLVJkvnWFGd53pYjz1cdwjZ8zGsZFZ143QdLIrw7R2d2urP3U7W0KMqPFDPSVpQIemed7KsiL3vyas9a/Wt212AdTLnRfUt4iKWOCTEgPUkVBBI96meqkYJ1XwABIuw2i/h4JkvG2XYV0f1YnpUJKDVhO2Bi3mmKT03NfY7qOm2dPOvOl5vKPHfHk2F6Y9dmeC8NycC7zBYYa0ONQI5OgT0cWcX2Ms+bVXHzI+TyZeM6L/aCKeHvYLZ1hoMvaoubwAcyZzQAwdzVVcUBRO67foX0rJVBQku1eucxow/LkooB0xZ8BguML4Cf/aOYM34FqCvOWj5tFR++VdUNRJagmRxeTJV/mzl0y+w1VYYL29agkSWQfoQefNecDWds7HfgXx6ocPdKYtPg=
  - secure: B3Ny/LFRzNU+MR+qHGwXDEj9+pijOHb1z/4fLsMuYm9avjc+kBQyQ9fA52tazOkQWw4XqfN4A98jZp9pYX7WaPJYtGKzoNaCMWdbQXCwpTbzjrbMJYDW5rAJyozIUHwvNOBeXJ2qYgqavwWvj/yq0ejc4uyT/mw/deFQ5UaC3D19Qhr1skFiv7kP4rRzgj+lAF9wAKYisAgdv6bBTCS9pZCH+WZkB56IdDHyJBLu8JcIuLAC6pBB6oTXIQW8kXr4fqSyc0lfK+ZxRqZRPShkQEDqTdZ0cJV2f4IglDMuBFOIB5vb9zhl16CRCHjRi2UmnZDpFOyPNpa1lV7peOSpHj8zNE60/IIhaHh5ZgTgOZ2Bwd6Er6Fcr3AEzokBXCZtnorGs9pXQxgzQIc3wtFtGN6fMkKM45GKlXRjwIzua+vPJ/rbaLAdoHcVsEjMsMzzKrKOtx895wqm6xBLQj4I5/7J9ZsQjqwQGu4jVXKERZ81EoFpmY6MtUd/N+zJxKlFOHSMDgi/vbKsyvI4NvYh6YJZw+q6pefeZIhbbDPvKciqD+8OpiQRHW1KrcYSJs+WYkOT2fCltNgRm+C0et2nrUPEBI8lhB2YyF7YHnqgy5mZwjRzO7PrOhrIJGbs47/+OwxlS/TG8McxqdbjrDh9zKiZ72Q4O02LfvDOi1zuQ9o=
